# URL:     https://raw.githubusercontent.com/DesperadoJ/Rules-for-UnblockNeteaseMusic/master/Clash/UnblockNeteaseMusic.yaml
# Project: https://github.com/DesperadoJ/Rules-for-UnblockNeteaseMusic
# Note:    This proxy is for free, please complain the seller if you were charged
#          本代理完全免费，如遇收费请投诉举报卖家
# https://cdn.staticaly.com/gh/DesperadoJ/Rules-for-UnblockNeteaseMusic/master/Clash/Proxy/NeteaseMusic.yaml
# https://cdn.staticaly.com/gh/DesperadoJ/Rules-for-UnblockNeteaseMusic/master/Clash/RuleSet/NeteaseMusic.yaml

mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
    - 1.0.0.1
    - 8.8.4.4

proxies:
  - name: Unlock
    type: ss
    server: music.desperadoj.com
    port: 30001
    cipher: aes-128-gcm
    password: desperadoj.com_free_proxy_d39m


proxy-groups:
  - name: 🎵 网易云音乐
    type: select
    proxies:
      - DIRECT
      - Unlock

rules:
  # Netease Music Advertising
  - DOMAIN,admusicpic.music.126.net,REJECT
  - DOMAIN,iadmat.nosdn.127.net,REJECT
  - DOMAIN,iadmusicmat.music.126.net,REJECT
  - DOMAIN,iadmusicmatvideo.music.126.net,REJECT

  # Netease Music
  - DOMAIN,api.iplay.163.com,🎵 网易云音乐
  - DOMAIN,apm3.music.163.com,🎵 网易云音乐
  - DOMAIN,apm.music.163.com,🎵 网易云音乐
  - DOMAIN,interface3.music.163.com,🎵 网易云音乐
  - DOMAIN,interface3.music.163.com.163jiasu.com,🎵 网易云音乐
  - DOMAIN,interface.music.163.com,🎵 网易云音乐
  - DOMAIN,music.163.com,🎵 网易云音乐
  - IP-CIDR,39.105.63.80/32,🎵 网易云音乐,no-resolve
  - IP-CIDR,39.105.175.128/32,🎵 网易云音乐,no-resolve
  - IP-CIDR,45.254.48.1/32,🎵 网易云音乐,no-resolve
  - IP-CIDR,47.100.127.239/32,🎵 网易云音乐,no-resolve
  - IP-CIDR,59.111.19.33/32,🎵 网易云音乐,no-resolve
  - IP-CIDR,59.111.160.195/32,🎵 网易云音乐,no-resolve
  - IP-CIDR,59.111.160.197/32,🎵 网易云音乐,no-resolve
  - IP-CIDR,101.71.154.241/32,🎵 网易云音乐,no-resolve
  - IP-CIDR,103.126.92.132/32,🎵 网易云音乐,no-resolve
  - IP-CIDR,103.126.92.133/32,🎵 网易云音乐,no-resolve
  - IP-CIDR,112.13.119.18/32,🎵 网易云音乐,no-resolve
  - IP-CIDR,112.13.122.4/32,🎵 网易云音乐,no-resolve
  - IP-CIDR,115.236.118.34/32,🎵 网易云音乐,no-resolve
  - IP-CIDR,115.236.121.4/32,🎵 网易云音乐,no-resolve
  - IP-CIDR,118.24.63.156/32,🎵 网易云音乐,no-resolve
  - IP-CIDR,182.92.170.253/32,🎵 网易云音乐,no-resolve
  - IP-CIDR,193.112.159.225/32,🎵 网易云音乐,no-resolve

  # Final
  - MATCH,DIRECT
