name: 合并

on:
  workflow_dispatch:
  push:
    paths:
      - 'book_source/**'

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run Merge Script
        run: python3 ./.github/scripts/src_merge.py
        
      - name: Push
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "Robot"
          git add .
          git commit --allow-empty -m "update"
          git push origin main
 
      - name: Run Purge Cache Script
        run: |
          pip3 install requests
          python3 ./.github/scripts/purge_cache.py
 
